const LANGS={"no":{"name":"Norsk","nav":["Personvern","Brukerstøtte","FAQ","Kontakt"],"home":"Hjem"},"en":{"name":"English","nav":["Privacy","Support","FAQ","Contact"],"home":"Home"},"sv":{"name":"Svenska","nav":["Integritet","Support","FAQ","Kontakt"],"home":"Hem"},"da":{"name":"Dansk","nav":["Privatliv","Support","FAQ","Kontakt"],"home":"Hjem"},"de":{"name":"Deutsch","nav":["Datenschutz","Support","FAQ","Kontakt"],"home":"Start"},"pl":{"name":"Polski","nav":["Prywatność","Pomoc","FAQ","Kontakt"],"home":"Start"},"nl":{"name":"Nederlands","nav":["Privacy","Ondersteuning","FAQ","Contact"],"home":"Home"},"fi":{"name":"Suomi","nav":["Tietosuoja","Tuki","UKK","Yhteystiedot"],"home":"Etusivu"}};
const PAGES=["home","privacy","support","faq","contact"],PAGE_PATH={home:"",privacy:"privacy",support:"support",faq:"faq",contact:"contact"};
function route(){const p=location.pathname.split("/").filter(Boolean);let lang="no",page="home";if(p.length&&LANGS[p[0]])lang=p.shift();if(p.length&&PAGES.includes(p[0]))page=p[0];return{lang,page}}
function pathFor(lang,page){return(lang==="no"?"":`/${lang}`)+(PAGE_PATH[page]?`/${PAGE_PATH[page]}/`:"/")}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function pairs(items,cls="section-list"){return`<div class="${cls}">${items.map(([a,b])=>`<section class="info-card"><h2>${esc(a)}</h2><p>${esc(b)}</p></section>`).join("")}</div>`}
function logoImage(className,alt){return`<img class="${className}" data-brand-image alt="${esc(alt)}">`}
function header(lang,page){const l=LANGS[lang],ps=["privacy","support","faq","contact"];return`<header class="site-header"><div class="container header-inner"><a class="brand" href="${pathFor(lang,"home")}">${logoImage("brand-logo","")}<span>Concrete Cutter</span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="main-nav">☰</button><nav id="main-nav">${ps.map((p,i)=>`<a ${page===p?'aria-current="page"':""} href="${pathFor(lang,p)}">${esc(l.nav[i])}</a>`).join("")}</nav><label class="language-picker"><span class="sr-only">Language</span><select id="language-select" aria-label="Language">${Object.entries(LANGS).map(([c,d])=>`<option value="${c}" ${c===lang?"selected":""}>${esc(d.name)}</option>`).join("")}</select></label></div></header>`}
function home(t,lang){return`<main><section class="hero"><div class="container hero-grid"><div><p class="eyebrow">Concrete Cutter Apps</p><h1>${esc(t.hero_title)}</h1><p class="lead">${esc(t.hero_lead)}</p><div class="hero-actions"><a class="button primary" href="${pathFor(lang,"support")}">${esc(LANGS[lang].nav[1])}</a><a class="button secondary" href="${pathFor(lang,"privacy")}">${esc(LANGS[lang].nav[0])}</a></div></div><div class="brand-showcase">${logoImage("hero-logo","Concrete Cutter")}</div></div></section><section class="container content-block"><p class="eyebrow">Concrete Cutter</p><h2 class="section-heading">${esc(t.features_title)}</h2>${pairs(t.features,"feature-grid")}</section><section class="container content-block"><div class="link-grid">${["privacy","support","faq","contact"].map((p,i)=>`<a class="link-card" href="${pathFor(lang,p)}"><h2>${esc(t.cards[i][0])}</h2><p>${esc(t.cards[i][1])}</p><span>→</span></a>`).join("")}</div></section></main>`}
function pageContent(t,lang,page){let title="",intro="",body="";if(page==="privacy"){title=t.privacy_title;intro=t.privacy_intro;body=`<p class="eyebrow">${esc(t.updated)}</p>`+pairs(t.privacy_sections)}if(page==="support"){title=t.support_title;intro=t.support_intro;body=pairs(t.support_sections)}if(page==="faq"){title=t.faq_title;body=`<div class="faq-list">${t.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join("")}</div>`}if(page==="contact"){title=t.contact_title;intro=t.contact_intro;body=pairs(t.contact_sections)}return`<main class="container content page"><a class="back-link" href="${pathFor(lang,"home")}">← ${esc(LANGS[lang].home)}</a><h1>${esc(title)}</h1>${intro?`<p class="lead narrow">${esc(intro)}</p>`:""}${body}</main>`}
async function loadBrandAssets(){try{const encoded=(await fetch("/assets/logo-horizontal.webp")).text();const base64=(await encoded).trim();const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:"image/webp"}));document.querySelectorAll("[data-brand-image]").forEach(image=>{image.src=url})}catch(error){console.warn("Could not load brand image",error)}}
function render(){const{lang,page}=route(),t=window.CC_TEXT[lang]||window.CC_TEXT.no;document.documentElement.lang=lang;document.title=page==="home"?"Concrete Cutter":`${page==="privacy"?t.privacy_title:page==="support"?t.support_title:page==="faq"?t.faq_title:t.contact_title} – Concrete Cutter`;document.querySelector('meta[name="description"]').content=t.meta;document.getElementById("app").innerHTML=header(lang,page)+(page==="home"?home(t,lang):pageContent(t,lang,page))+`<footer><div class="container">© 2026 ${esc(t.footer)}</div></footer>`;const m=document.querySelector(".menu-button"),n=document.getElementById("main-nav");m.addEventListener("click",()=>{const o=m.getAttribute("aria-expanded")==="true";m.setAttribute("aria-expanded",String(!o));n.classList.toggle("open",!o)});document.getElementById("language-select").addEventListener("change",e=>{localStorage.setItem("cc-language",e.target.value);location.href=pathFor(e.target.value,page)});loadBrandAssets()}
async function boot(){const s=document.createElement("script");s.src="/data.js";s.onload=async()=>{const bytes=Uint8Array.from(atob(window.CC_DATA_GZ),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));window.CC_TEXT=JSON.parse(await new Response(stream).text());render()};s.onerror=()=>{document.getElementById("app").innerHTML="<main class='container content'><h1>Concrete Cutter</h1><p>Unable to load website content.</p></main>"};document.head.appendChild(s)}
boot();
